"use client";
import * as React from "react";
import { CheckIcon, ChevronDownIcon, ChevronUpIcon } from "lucide-react";
import { Select as SelectPrimitive } from "radix-ui";
import { cn } from "@/lib/utils";
function Select(props:React.ComponentProps<typeof SelectPrimitive.Root>){return <SelectPrimitive.Root {...props}/>}
function SelectValue(props:React.ComponentProps<typeof SelectPrimitive.Value>){return <SelectPrimitive.Value {...props}/>}
function SelectTrigger({className,children,...props}:React.ComponentProps<typeof SelectPrimitive.Trigger>){return <SelectPrimitive.Trigger className={cn("flex w-fit items-center justify-between gap-2 rounded-md border border-input bg-transparent px-3 py-2 text-sm outline-none",className)} {...props}>{children}<SelectPrimitive.Icon asChild><ChevronDownIcon className="size-4 opacity-50"/></SelectPrimitive.Icon></SelectPrimitive.Trigger>}
function SelectContent({className,children,...props}:React.ComponentProps<typeof SelectPrimitive.Content>){return <SelectPrimitive.Portal><SelectPrimitive.Content className={cn("relative z-50 max-h-96 min-w-[8rem] overflow-y-auto rounded-md border bg-popover text-popover-foreground shadow-md",className)} {...props}><SelectPrimitive.ScrollUpButton className="flex items-center justify-center py-1"><ChevronUpIcon className="size-4"/></SelectPrimitive.ScrollUpButton><SelectPrimitive.Viewport className="p-1">{children}</SelectPrimitive.Viewport><SelectPrimitive.ScrollDownButton className="flex items-center justify-center py-1"><ChevronDownIcon className="size-4"/></SelectPrimitive.ScrollDownButton></SelectPrimitive.Content></SelectPrimitive.Portal>}
function SelectItem({className,children,...props}:React.ComponentProps<typeof SelectPrimitive.Item>){return <SelectPrimitive.Item className={cn("relative flex w-full cursor-default items-center py-1.5 pr-8 pl-2 text-sm outline-none focus:bg-accent",className)} {...props}><span className="absolute right-2 flex size-3.5 items-center justify-center"><SelectPrimitive.ItemIndicator><CheckIcon className="size-4"/></SelectPrimitive.ItemIndicator></span><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>}
export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue };
